from AmprexTestingGrounds import Mod
MODS = [
        #-----------Empties-----------#
        Mod("EmptyMod", {}, 0, "EmptyMod", canBeDuplicated=True, tags=[]),
        #-----------------------------#

        
        Mod("Serration", {"BonusDamagePercent": 0.15}, 4, "Serration"),
        Mod("Serration1", {"BonusDamagePercent": 0.3}, 5, "Serration"),
        Mod("Serration2", {"BonusDamagePercent": 0.45}, 6, "Serration"),
        Mod("Serration3", {"BonusDamagePercent": 0.6}, 7, "Serration"),
        Mod("Serration4", {"BonusDamagePercent": 0.75}, 8, "Serration"),
        Mod("Serration5", {"BonusDamagePercent": 0.9}, 9, "Serration"),
        Mod("Serration6", {"BonusDamagePercent": 1.05}, 10, "Serration"),
        Mod("Serration7", {"BonusDamagePercent": 1.2}, 11, "Serration"),
        Mod("Serration8", {"BonusDamagePercent": 1.35}, 12, "Serration"),
        Mod("Serration9", {"BonusDamagePercent": 1.5}, 13, "Serration"),
        Mod("Serration10", {"BonusDamagePercent": 1.65}, 14, "Serration"),

        Mod("CriticalDelay", {"BonusCritChance": 0.333, "BonusFireRate": -0.033}, 4, "CriticalDelay", ["PointStrike"]),
        Mod("CriticalDelay1", {"BonusCritChance": 0.667, "BonusFireRate": -0.067}, 5, "CriticalDelay", ["PointStrike"]),
        Mod("CriticalDelay2", {"BonusCritChance": 1, "BonusFireRate": -0.1}, 6, "CriticalDelay", ["PointStrike"]),
        Mod("CriticalDelay3", {"BonusCritChance": 1.333, "BonusFireRate": -0.133}, 7, "CriticalDelay", ["PointStrike"]),
        Mod("CriticalDelay4", {"BonusCritChance": 1.667, "BonusFireRate": -0.167}, 8, "CriticalDelay", ["PointStrike"]),
        Mod("CriticalDelay5", {"BonusCritChance": 2, "BonusFireRate": -0.2}, 9, "CriticalDelay", ["PointStrike"]),

        Mod("FastHands", {"BonusReload": -0.05}, 2, "FastHands"),
        Mod("FastHands1", {"BonusReload": -0.1}, 3, "FastHands"),
        Mod("FastHands2", {"BonusReload": -0.15}, 4, "FastHands"),
        Mod("FastHands3", {"BonusReload": -0.2}, 5, "FastHands"),
        Mod("FastHands4", {"BonusReload": -0.25}, 6, "FastHands"),
        Mod("FastHands5", {"BonusReload": -0.3}, 7, "FastHands"),

        Mod("Hellfire", {"BonusHeat": 0.15}, 6, "Hellfire"),
        Mod("Hellfire1", {"BonusHeat": 0.3}, 7, "Hellfire"),
        Mod("Hellfire2", {"BonusHeat": 0.45}, 8, "Hellfire"),
        Mod("Hellfire3", {"BonusHeat": 0.6}, 9, "Hellfire"),
        Mod("Hellfire4", {"BonusHeat": 0.75}, 10, "Hellfire"),
        Mod("Hellfire5", {"BonusHeat": 0.9}, 11, "Hellfire"),

        Mod("InfectedClip", {"BonusToxin": 0.15}, 6, "InfectedClip"),
        Mod("InfectedClip1", {"BonusToxin": 0.3}, 7, "InfectedClip"),
        Mod("InfectedClip2", {"BonusToxin": 0.45}, 8, "InfectedClip"),
        Mod("InfectedClip3", {"BonusToxin": 0.6}, 9, "InfectedClip"),
        Mod("InfectedClip4", {"BonusToxin": 0.75}, 10, "InfectedClip"),
        Mod("InfectedClip5", {"BonusToxin": 0.9}, 11, "InfectedClip"),

        Mod("MagazineWarp", {"BonusMagazine": 0.05}, 4, "MagazineWarp"),
        Mod("MagazineWarp1", {"BonusMagazine": 0.1}, 5, "MagazineWarp"),
        Mod("MagazineWarp2", {"BonusMagazine": 0.15}, 6, "MagazineWarp"),
        Mod("MagazineWarp3", {"BonusMagazine": 0.2}, 7, "MagazineWarp"),
        Mod("MagazineWarp4", {"BonusMagazine": 0.25}, 8, "MagazineWarp"),
        Mod("MagazineWarp5", {"BonusMagazine": 0.3}, 9, "MagazineWarp"),

        Mod("Stormbringer", {"BonusElectricity": 0.15}, 6, "Stormbringer"),
        Mod("Stormbringer1", {"BonusElectricity": 0.3}, 7, "Stormbringer"),
        Mod("Stormbringer2", {"BonusElectricity": 0.45}, 8, "Stormbringer"),
        Mod("Stormbringer3", {"BonusElectricity": 0.6}, 9, "Stormbringer"),
        Mod("Stormbringer4", {"BonusElectricity": 0.75}, 10, "Stormbringer"),
        Mod("Stormbringer5", {"BonusElectricity": 0.9}, 11, "Stormbringer"),

        Mod("CryoRounds", {"BonusCold": 0.15}, 6, "CryoRounds", "PrimedCryoRounds"),
        Mod("CryoRounds1", {"BonusCold": 0.3}, 7, "CryoRounds", "PrimedCryoRounds"),
        Mod("CryoRounds2", {"BonusCold": 0.45}, 8, "CryoRounds", "PrimedCryoRounds"),
        Mod("CryoRounds3", {"BonusCold": 0.6}, 9, "CryoRounds", "PrimedCryoRounds"),
        Mod("CryoRounds4", {"BonusCold": 0.75}, 10, "CryoRounds", "PrimedCryoRounds"),
        Mod("CryoRounds5", {"BonusCold": 0.9}, 11, "CryoRounds", "PrimedCryoRounds"),

        Mod("TaintedMag", {"BonusReload": -0.03, "BonusMagazine": 0.06}, 4, "TaintedMag"),
        Mod("TaintedMag1", {"BonusReload": -0.06, "BonusMagazine": 0.12}, 5, "TaintedMag"),
        Mod("TaintedMag2", {"BonusReload": -0.09, "BonusMagazine": 0.18}, 6, "TaintedMag"),
        Mod("TaintedMag3", {"BonusReload": -0.12, "BonusMagazine": 0.24}, 7, "TaintedMag"),
        Mod("TaintedMag4", {"BonusReload": -0.15, "BonusMagazine": 0.3}, 8, "TaintedMag"),
        Mod("TaintedMag5", {"BonusReload": -0.18, "BonusMagazine": 0.36}, 9, "TaintedMag"),
        Mod("TaintedMag6", {"BonusReload": -0.21, "BonusMagazine": 0.42}, 10, "TaintedMag"),
        Mod("TaintedMag7", {"BonusReload": -0.24, "BonusMagazine": 0.48}, 11, "TaintedMag"),
        Mod("TaintedMag8", {"BonusReload": -0.27, "BonusMagazine": 0.54}, 12, "TaintedMag"),
        Mod("TaintedMag9", {"BonusReload": -0.3, "BonusMagazine": 0.6}, 13, "TaintedMag"),
        Mod("TaintedMag10", {"BonusReload": -0.33, "BonusMagazine": 0.66}, 14, "TaintedMag"),

        Mod("PrimedCryoRounds", {"BonusCold": 0.15}, 6, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds1", {"BonusCold": 0.3}, 7, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds2", {"BonusCold": 0.45}, 8, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds3", {"BonusCold": 0.6}, 9, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds4", {"BonusCold": 0.75}, 10, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds5", {"BonusCold": 0.9}, 11, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds6", {"BonusCold": 1.05}, 12, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds7", {"BonusCold": 1.2}, 13, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds8", {"BonusCold": 1.35}, 14, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds9", {"BonusCold": 1.5}, 15, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds10", {"BonusCold": 1.65}, 16, "PrimedCryoRounds", ["CryoRounds"]),

        Mod("RifleAmplitude", {"BonusStatusChance": 0.15}, 4, "RifleAmplitude"),
        Mod("RifleAmplitude1", {"BonusStatusChance": 0.3}, 5, "RifleAmplitude"),
        Mod("RifleAmplitude2", {"BonusStatusChance": 0.45}, 6, "RifleAmplitude"),
        Mod("RifleAmplitude3", {"BonusStatusChance": 0.6}, 7, "RifleAmplitude"),
        Mod("RifleAmplitude4", {"BonusStatusChance": 0.75}, 8, "RifleAmplitude"),
        Mod("RifleAmplitude5", {"BonusStatusChance": 0.9}, 9, "RifleAmplitude"),

        Mod("HeavyCaliber", {"BonusDamagePercent": 0.15}, 6, "HeavyCaliber"),
        Mod("HeavyCaliber1", {"BonusDamagePercent": 0.3}, 7, "HeavyCaliber"),
        Mod("HeavyCaliber2", {"BonusDamagePercent": 0.45}, 8, "HeavyCaliber"),
        Mod("HeavyCaliber3", {"BonusDamagePercent": 0.6}, 9, "HeavyCaliber"),
        Mod("HeavyCaliber4", {"BonusDamagePercent": 0.75}, 10, "HeavyCaliber"),
        Mod("HeavyCaliber5", {"BonusDamagePercent": 0.9}, 11, "HeavyCaliber"),
        Mod("HeavyCaliber6", {"BonusDamagePercent": 1.05}, 12, "HeavyCaliber"),
        Mod("HeavyCaliber7", {"BonusDamagePercent": 1.2}, 13, "HeavyCaliber"),
        Mod("HeavyCaliber8", {"BonusDamagePercent": 1.35}, 14, "HeavyCaliber"),
        Mod("HeavyCaliber9", {"BonusDamagePercent": 1.5}, 15, "HeavyCaliber"),
        Mod("HeavyCaliber10", {"BonusDamagePercent": 1.65}, 16, "HeavyCaliber"),

        Mod("MalignantForce", {"BonusToxin": 0.15, "BonusStatusChance": 0.15}, 4, "MalignantForce"),
        Mod("MalignantForce1", {"BonusToxin": 0.3, "BonusStatusChance": 0.3}, 5, "MalignantForce"),
        Mod("MalignantForce2", {"BonusToxin": 0.45, "BonusStatusChance": 0.45}, 6, "MalignantForce"),
        Mod("MalignantForce3", {"BonusToxin": 0.6, "BonusStatusChance": 0.6}, 7, "MalignantForce"),

        Mod("PointStrike", {"BonusCritChance": 0.25}, 4, "PointStrike", ["CriticalDelay"]),
        Mod("PointStrike1", {"BonusCritChance": 0.5}, 5, "PointStrike", ["CriticalDelay"]),
        Mod("PointStrike2", {"BonusCritChance": 0.75}, 6, "PointStrike", ["CriticalDelay"]),
        Mod("PointStrike3", {"BonusCritChance": 1}, 7, "PointStrike", ["CriticalDelay"]),
        Mod("PointStrike4", {"BonusCritChance": 1.25}, 8, "PointStrike", ["CriticalDelay"]),
        Mod("PointStrike5", {"BonusCritChance": 1.5}, 9, "PointStrike", ["CriticalDelay"]),

        Mod("SpeedTrigger", {"BonusFireRate": 0.10}, 4, "SpeedTrigger"),
        Mod("SpeedTrigger1", {"BonusFireRate": 0.20}, 5, "SpeedTrigger"),
        Mod("SpeedTrigger2", {"BonusFireRate": 0.30}, 6, "SpeedTrigger"),
        Mod("SpeedTrigger3", {"BonusFireRate": 0.40}, 7, "SpeedTrigger"),
        Mod("SpeedTrigger4", {"BonusFireRate": 0.50}, 8, "SpeedTrigger"),
        Mod("SpeedTrigger5", {"BonusFireRate": 0.60}, 9, "SpeedTrigger"),

        Mod("SplitChamber", {"BonusMultishot": 0.15}, 10, "SplitChamber"),
        Mod("SplitChamber1", {"BonusMultishot": 0.3}, 11, "SplitChamber"),
        Mod("SplitChamber2", {"BonusMultishot": 0.45}, 12, "SplitChamber"),
        Mod("SplitChamber3", {"BonusMultishot": 0.6}, 13, "SplitChamber"),
        Mod("SplitChamber4", {"BonusMultishot": 0.75}, 14, "SplitChamber"),
        Mod("SplitChamber5", {"BonusMultishot": 0.9}, 15, "SplitChamber"),

        Mod("VitalSense", {"BonusCritMultiplier": 0.20}, 4, "VitalSense"),
        Mod("VitalSense1", {"BonusCritMultiplier": 0.40}, 5, "VitalSense"),
        Mod("VitalSense2", {"BonusCritMultiplier": 0.60}, 6, "VitalSense"),
        Mod("VitalSense3", {"BonusCritMultiplier": 0.80}, 7, "VitalSense"),
        Mod("VitalSense4", {"BonusCritMultiplier": 1.00}, 8, "VitalSense"),
        Mod("VitalSense5", {"BonusCritMultiplier": 1.20}, 9, "VitalSense"),

        Mod("Wildfire", {"BonusHeat": 0.15, "BonusMagazine": 0.05}, 6, "Wildfire"),
        Mod("Wildfire1", {"BonusHeat": 0.3, "BonusMagazine": 0.1}, 7, "Wildfire"),
        Mod("Wildfire2", {"BonusHeat": 0.45, "BonusMagazine": 0.15}, 8, "Wildfire"),
        Mod("Wildfire3", {"BonusHeat": 0.6, "BonusMagazine": 0.2}, 9, "Wildfire"),

        Mod("PiercingHit", {"BonusPuncture": 0.15}, 4, "PiercingHit"),
        Mod("PiercingHit1", {"BonusPuncture": 0.3}, 5, "PiercingHit"),
        Mod("PiercingHit2", {"BonusPuncture": 0.45}, 6, "PiercingHit"),
        Mod("PiercingHit3", {"BonusPuncture": 0.6}, 7, "PiercingHit"),
        Mod("PiercingHit4", {"BonusPuncture": 0.75}, 8, "PiercingHit"),
        Mod("PiercingHit5", {"BonusPuncture": 0.9}, 9, "PiercingHit"),

        Mod("RifleAptitude", {"BonusStatusChance": 0.15}, 4, "RifleAptitude"),
        Mod("RifleAptitude1", {"BonusStatusChance": 0.3}, 5, "RifleAptitude"),
        Mod("RifleAptitude2", {"BonusStatusChance": 0.45}, 6, "RifleAptitude"),
        Mod("RifleAptitude3", {"BonusStatusChance": 0.6}, 7, "RifleAptitude"),
        Mod("RifleAptitude4", {"BonusStatusChance": 0.75}, 8, "RifleAptitude"),
        Mod("RifleAptitude5", {"BonusStatusChance": 0.9}, 9, "RifleAptitude"),

        Mod("SawtoothClip", {"BonusSlash": 0.15}, 4, "SawtoothClip"),
        Mod("SawtoothClip1", {"BonusSlash": 0.3}, 5, "SawtoothClip"),
        Mod("SawtoothClip2", {"BonusSlash": 0.45}, 6, "SawtoothClip"),
        Mod("SawtoothClip3", {"BonusSlash": 0.6}, 7, "SawtoothClip"),
        Mod("SawtoothClip4", {"BonusSlash": 0.75}, 8, "SawtoothClip"),
        Mod("SawtoothClip5", {"BonusSlash": 0.9}, 9, "SawtoothClip"),

        Mod("Rupture", {"BonusImpact": 0.15}, 4, "Rupture"),
        Mod("Rupture1", {"BonusImpact": 0.3}, 5, "Rupture"),
        Mod("Rupture2", {"BonusImpact": 0.45}, 6, "Rupture"),
        Mod("Rupture3", {"BonusImpact": 0.6}, 7, "Rupture"),
        Mod("Rupture4", {"BonusImpact": 0.75}, 8, "Rupture"),
        Mod("Rupture5", {"BonusImpact": 0.9}, 9, "Rupture"),

        Mod("CrashCourse", {"BonusImpact": 0.2}, 4, "CrashCourse"),
        Mod("CrashCourse1", {"BonusImpact": 0.4}, 5, "CrashCourse"),
        Mod("CrashCourse2", {"BonusImpact": 0.6}, 6, "CrashCourse"),
        Mod("CrashCourse3", {"BonusImpact": 0.8}, 7, "CrashCourse"),
        Mod("CrashCourse4", {"BonusImpact": 1}, 8, "CrashCourse"),
        Mod("CrashCourse5", {"BonusImpact": 1.2}, 9, "CrashCourse"),

        Mod("HornetStrike", {"BonusDamagePercent": 0.2}, 4, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike1", {"BonusDamagePercent": 0.4}, 5, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike2", {"BonusDamagePercent": 0.6}, 6, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike3", {"BonusDamagePercent": 0.8}, 7, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike4", {"BonusDamagePercent": 1}, 8, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike5", {"BonusDamagePercent": 1.2}, 9, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike6", {"BonusDamagePercent": 1.4}, 10, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike7", {"BonusDamagePercent": 1.6}, 11, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike8", {"BonusDamagePercent": 1.8}, 12, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike9", {"BonusDamagePercent": 2}, 13, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike10", {"BonusDamagePercent": 2.2}, 14, "HornetStrike", tags = ["pistol"]),

        Mod("BarrelDiffusion", {"BonusMultishot": 0.2}, 6, "BarrelDiffusion", tags = ["pistol"]),
        Mod("BarrelDiffusion1", {"BonusMultishot": 0.4}, 7, "BarrelDiffusion", tags = ["pistol"]),
        Mod("BarrelDiffusion2", {"BonusMultishot": 0.6}, 8, "BarrelDiffusion", tags = ["pistol"]),
        Mod("BarrelDiffusion3", {"BonusMultishot": 0.8}, 9, "BarrelDiffusion", tags = ["pistol"]),
        Mod("BarrelDiffusion4", {"BonusMultishot": 1}, 10, "BarrelDiffusion", tags = ["pistol"]),
        Mod("BarrelDiffusion5", {"BonusMultishot": 1.2}, 11, "BarrelDiffusion", tags = ["pistol"]),

        Mod("Convulsion", {"BonusElectricity": 0.15}, 6, "Convulsion", tags = ["pistol"]),
        Mod("Convulsion1", {"BonusElectricity": 0.3}, 7, "Convulsion", tags = ["pistol"]),
        Mod("Convulsion2", {"BonusElectricity": 0.45}, 8, "Convulsion", tags = ["pistol"]),
        Mod("Convulsion3", {"BonusElectricity": 0.6}, 9, "Convulsion", tags = ["pistol"]),
        Mod("Convulsion4", {"BonusElectricity": 0.75}, 10, "Convulsion", tags = ["pistol"]),
        Mod("Convulsion5", {"BonusElectricity": 0.9}, 11, "Convulsion", tags = ["pistol"]),

        Mod("HeatedCharge", {"BonusHeat": 0.15}, 6, "HeatedCharge", tags = ["pistol"]),
        Mod("HeatedCharge1", {"BonusHeat": 0.3}, 7, "HeatedCharge", tags = ["pistol"]),
        Mod("HeatedCharge2", {"BonusHeat": 0.45}, 8, "HeatedCharge", tags = ["pistol"]),
        Mod("HeatedCharge3", {"BonusHeat": 0.6}, 9, "HeatedCharge", tags = ["pistol"]),
        Mod("HeatedCharge4", {"BonusHeat": 0.75}, 10, "HeatedCharge", tags = ["pistol"]),
        Mod("HeatedCharge5", {"BonusHeat": 0.9}, 11, "HeatedCharge", tags = ["pistol"]),

        Mod("PathogenRounds", {"BonusToxin": 0.15}, 6, "PathogenRounds", tags = ["pistol"]),
        Mod("PathogenRounds1", {"BonusToxin": 0.3}, 7, "PathogenRounds", tags = ["pistol"]),
        Mod("PathogenRounds2", {"BonusToxin": 0.45}, 8, "PathogenRounds", tags = ["pistol"]),
        Mod("PathogenRounds3", {"BonusToxin": 0.6}, 9, "PathogenRounds", tags = ["pistol"]),
        Mod("PathogenRounds4", {"BonusToxin": 0.75}, 10, "PathogenRounds", tags = ["pistol"]),
        Mod("PathogenRounds5", {"BonusToxin": 0.9}, 11, "PathogenRounds", tags = ["pistol"]),
        
        Mod("Gunslinger", {"BonusFireRate": 0.12}, 4, "Gunslinger", tags = ["pistol"]),
        Mod("Gunslinger1", {"BonusFireRate": 0.24}, 5, "Gunslinger", tags = ["pistol"]),
        Mod("Gunslinger2", {"BonusFireRate": 0.36}, 6, "Gunslinger", tags = ["pistol"]),
        Mod("Gunslinger3", {"BonusFireRate": 0.48}, 7, "Gunslinger", tags = ["pistol"]),
        Mod("Gunslinger4", {"BonusFireRate": 0.6}, 8, "Gunslinger", tags = ["pistol"]),
        Mod("Gunslinger5", {"BonusFireRate": 0.72}, 9, "Gunslinger", tags = ["pistol"]),

        Mod("PistolGambit", {"BonusCritChance" : 0.2}, 4, "PistolGambit", tags = ["pistol"]),
        Mod("PistolGambit1", {"BonusCritChance" : 0.4}, 5, "PistolGambit", tags = ["pistol"]),
        Mod("PistolGambit2", {"BonusCritChance" : 0.6}, 6, "PistolGambit", tags = ["pistol"]),
        Mod("PistolGambit3", {"BonusCritChance" : 0.8}, 7, "PistolGambit", tags = ["pistol"]),
        Mod("PistolGambit4", {"BonusCritChance" : 1}, 8, "PistolGambit", tags = ["pistol"]),
        Mod("PistolGambit5", {"BonusCritChance" : 1.2}, 9, "PistolGambit", tags = ["pistol"]),

        Mod("SlipMagazine", {"BonusMagazine": 0.05}, 4, "SlipMagazine", tags = ["pistol"]),
        Mod("SlipMagazine1", {"BonusMagazine": 0.1}, 5, "SlipMagazine", tags = ["pistol"]),
        Mod("SlipMagazine2", {"BonusMagazine": 0.15}, 6, "SlipMagazine", tags = ["pistol"]),
        Mod("SlipMagazine3", {"BonusMagazine": 0.2}, 7, "SlipMagazine", tags = ["pistol"]),
        Mod("SlipMagazine4", {"BonusMagazine": 0.25}, 8, "SlipMagazine", tags = ["pistol"]),
        Mod("SlipMagazine5", {"BonusMagazine": 0.3}, 9, "SlipMagazine", tags = ["pistol"]),

        Mod("TargetCracker", {"BonusCritMultiplier": 0.1}, 4, "TargetCracker", tags = ["pistol"]),
        Mod("TargetCracker1", {"BonusCritMultiplier": 0.2}, 5, "TargetCracker", tags = ["pistol"]),
        Mod("TargetCracker2", {"BonusCritMultiplier": 0.3}, 6, "TargetCracker", tags = ["pistol"]),
        Mod("TargetCracker3", {"BonusCritMultiplier": 0.4}, 7, "TargetCracker", tags = ["pistol"]),
        Mod("TargetCracker4", {"BonusCritMultiplier": 0.5}, 8, "TargetCracker", tags = ["pistol"]),
        Mod("TargetCracker5", {"BonusCritMultiplier": 0.6}, 9, "TargetCracker", tags = ["pistol"]),

        Mod("ConcussionRounds", {"BonusImpact": 0.15}, 2, "ConcussionRounds", tags = ["pistol"]),
        Mod("ConcussionRounds1", {"BonusImpact": 0.3}, 3, "ConcussionRounds", tags = ["pistol"]),
        Mod("ConcussionRounds2", {"BonusImpact": 0.45}, 4, "ConcussionRounds", tags = ["pistol"]),
        Mod("ConcussionRounds3", {"BonusImpact": 0.6}, 5, "ConcussionRounds", tags = ["pistol"]),
        Mod("ConcussionRounds4", {"BonusImpact": 0.75}, 6, "ConcussionRounds", tags = ["pistol"]),
        Mod("ConcussionRounds5", {"BonusImpact": 0.9}, 7, "ConcussionRounds", tags = ["pistol"]),

        Mod("Quickdraw", {"BonusReload": 0.08}, 2, "Quickdraw", tags = ["pistol"]),
        Mod("Quickdraw1", {"BonusReload": 0.16}, 3, "Quickdraw", tags = ["pistol"]),
        Mod("Quickdraw2", {"BonusReload": 0.24}, 4, "Quickdraw", tags = ["pistol"]),
        Mod("Quickdraw3", {"BonusReload": 0.32}, 5, "Quickdraw", tags = ["pistol"]),
        Mod("Quickdraw4", {"BonusReload": 0.4}, 6, "Quickdraw", tags = ["pistol"]),
        Mod("Quickdraw5", {"BonusReload": 0.48}, 7, "Quickdraw", tags = ["pistol"]),

        Mod("RazorShot", {"BonusSlash": 0.15}, 2, "RazorShot", tags = ["pistol"]),
        Mod("RazorShot1", {"BonusSlash": 0.3}, 3, "RazorShot", tags = ["pistol"]),
        Mod("RazorShot2", {"BonusSlash": 0.45}, 4, "RazorShot", tags = ["pistol"]),
        Mod("RazorShot3", {"BonusSlash": 0.6}, 5, "RazorShot", tags = ["pistol"]),
        Mod("RazorShot4", {"BonusSlash": 0.75}, 6, "RazorShot", tags = ["pistol"]),
        Mod("RazorShot5", {"BonusSlash": 0.9}, 7, "RazorShot", tags = ["pistol"]),

        Mod("SureShot", {"BonusStatusChance": 0.15}, 2, "SureShot", tags = ["pistol"]),
        Mod("SureShot1", {"BonusStatusChance": 0.3}, 3, "SureShot", tags = ["pistol"]),
        Mod("SureShot2", {"BonusStatusChance": 0.45}, 4, "SureShot", tags = ["pistol"]),
        Mod("SureShot3", {"BonusStatusChance": 0.6}, 5, "SureShot", tags = ["pistol"]),
        Mod("SureShot4", {"BonusStatusChance": 0.75}, 6, "SureShot", tags = ["pistol"]),
        Mod("SureShot5", {"BonusStatusChance": 0.9}, 7, "SureShot", tags = ["pistol"]),

        Mod("DeepFreeze", {"BonusCold": 0.15}, 6, "DeepFreeze", tags = ["pistol"]),
        Mod("DeepFreeze1", {"BonusCold": 0.3}, 7, "DeepFreeze", tags = ["pistol"]),
        Mod("DeepFreeze2", {"BonusCold": 0.45}, 8, "DeepFreeze", tags = ["pistol"]),
        Mod("DeepFreeze3", {"BonusCold": 0.6}, 9, "DeepFreeze", tags = ["pistol"]),
        Mod("DeepFreeze4", {"BonusCold": 0.75}, 10, "DeepFreeze", tags = ["pistol"]),
        Mod("DeepFreeze5", {"BonusCold": 0.9}, 11, "DeepFreeze", tags = ["pistol"]),

        Mod("StunningSpeed", {"BonusReloadSpeed": 0.1, "BonusStatusChance": 0.075}, 6, "StunningSpeed", tags = ["pistol"]),
        Mod("StunningSpeed1", {"BonusReloadSpeed": 0.2, "BonusStatusChance": 0.15}, 7, "StunningSpeed", tags = ["pistol"]),
        Mod("StunningSpeed2", {"BonusReloadSpeed": 0.3, "BonusStatusChance": 0.225}, 8, "StunningSpeed", tags = ["pistol"]),
        Mod("StunningSpeed3", {"BonusReloadSpeed": 0.4, "BonusStatusChance": 0.3}, 9, "StunningSpeed", tags = ["pistol"]),

        Mod("AnemicAgility", {"BonusFireRate": 0.15, "BonusDamage": -0.025}, 4, "AnemicAgility", tags = ["pistol"]),
        Mod("AnemicAgility1", {"BonusFireRate": 0.3, "BonusDamage": -0.05}, 5, "AnemicAgility", tags = ["pistol"]),
        Mod("AnemicAgility2", {"BonusFireRate": 0.45, "BonusDamage": -0.075}, 6, "AnemicAgility", tags = ["pistol"]),
        Mod("AnemicAgility3", {"BonusFireRate": 0.6, "BonusDamage": -0.1}, 7, "AnemicAgility", tags = ["pistol"]),
        Mod("AnemicAgility4", {"BonusFireRate": 0.75, "BonusDamage": -0.125}, 8, "AnemicAgility", tags = ["pistol"]),
        Mod("AnemicAgility5", {"BonusFireRate": 0.9, "BonusDamage": -0.15}, 9, "AnemicAgility", tags = ["pistol"]),

        Mod("HollowPoint", {"BonusDamage": -0.025, "BonusCritMultiplier": 0.1}, 4, "HollowPoint", tags = ["pistol"]),
        Mod("HollowPoint1", {"BonusDamage": -0.05, "BonusCritMultiplier": 0.2}, 5, "HollowPoint", tags = ["pistol"]),
        Mod("HollowPoint2", {"BonusDamage": -0.075, "BonusCritMultiplier": 0.3}, 6, "HollowPoint", tags = ["pistol"]),
        Mod("HollowPoint3", {"BonusDamage": -0.1, "BonusCritMultiplier": 0.4}, 7, "HollowPoint", tags = ["pistol"]),
        Mod("HollowPoint4", {"BonusDamage": -0.125, "BonusCritMultiplier": 0.5}, 8, "HollowPoint", tags = ["pistol"]),
        Mod("HollowPoint5", {"BonusDamage": -0.15, "BonusCritMultiplier": 0.6}, 9, "HollowPoint", tags = ["pistol"]),

        Mod("NoReturn", {"BonusPuncture": 0.15}, 2, "No Return", tags = ["pistol"]),
        Mod("NoReturn1", {"BonusPuncture": 0.3}, 3, "No Return", tags = ["pistol"]),
        Mod("NoReturn2", {"BonusPuncture": 0.45}, 4, "No Return", tags = ["pistol"]),
        Mod("NoReturn3", {"BonusPuncture": 0.6}, 5, "No Return", tags = ["pistol"]),
        Mod("NoReturn4", {"BonusPuncture": 0.75}, 6, "No Return", tags = ["pistol"]),
        Mod("NoReturn5", {"BonusPuncture": 0.9}, 7, "No Return", tags = ["pistol"]),

        Mod("PistolPestilence", {"BonusToxin": 0.15, "BonusStatusChance": 0.15}, 4, "PistolPestilence", tags = ["pistol"]),
        Mod("PistolPestilence1", {"BonusToxin": 0.3, "BonusStatusChance": 0.3}, 5, "PistolPestilence", tags = ["pistol"]),
        Mod("PistolPestilence2", {"BonusToxin": 0.45, "BonusStatusChance": 0.45}, 6, "PistolPestilence", tags = ["pistol"]),
        Mod("PistolPestilence3", {"BonusToxin": 0.6, "BonusStatusChance": 0.6}, 7, "PistolPestilence", tags = ["pistol"]),

        Mod("PrimedTargetCracker", {"BonusCritMultiplier": 0.1}, 4, "PrimedTargetCracker", tags = ["pistol"]),
        Mod("PrimedTargetCracker1", {"BonusCritMultiplier": 0.2}, 5, "PrimedTargetCracker", tags = ["pistol"]),
        Mod("PrimedTargetCracker2", {"BonusCritMultiplier": 0.3}, 6, "PrimedTargetCracker", tags = ["pistol"]),
        Mod("PrimedTargetCracker3", {"BonusCritMultiplier": 0.4}, 7, "PrimedTargetCracker", tags = ["pistol"]),
        Mod("PrimedTargetCracker4", {"BonusCritMultiplier": 0.5}, 8, "PrimedTargetCracker", tags = ["pistol"]),
        Mod("PrimedTargetCracker5", {"BonusCritMultiplier": 0.6}, 9, "PrimedTargetCracker", tags = ["pistol"]),
        Mod("PrimedTargetCracker6", {"BonusCritMultiplier": 0.7}, 10, "PrimedTargetCracker", tags = ["pistol"]),
        Mod("PrimedTargetCracker7", {"BonusCritMultiplier": 0.8}, 11, "PrimedTargetCracker", tags = ["pistol"]),
        Mod("PrimedTargetCracker8", {"BonusCritMultiplier": 0.9}, 12, "PrimedTargetCracker", tags = ["pistol"]),
        Mod("PrimedTargetCracker9", {"BonusCritMultiplier": 1}, 13, "PrimedTargetCracker", tags = ["pistol"]),
        Mod("PrimedTargetCracker10", {"BonusCritMultiplier": 1.1}, 14, "PrimedTargetCracker", tags = ["pistol"]),

        Mod("AugurPact", {"BonusDamagePercent": 0.15}, 2, "AugurPact", tags = ["pistol"]),
        Mod("AugurPact1", {"BonusDamagePercent": 0.3}, 3, "AugurPact", tags = ["pistol"]),
        Mod("AugurPact2", {"BonusDamagePercent": 0.45}, 4, "AugurPact", tags = ["pistol"]),
        Mod("AugurPact3", {"BonusDamagePercent": 0.6}, 5, "AugurPact", tags = ["pistol"]),
        Mod("AugurPact4", {"BonusDamagePercent": 0.75}, 6, "AugurPact", tags = ["pistol"]),
        Mod("AugurPact5", {"BonusDamagePercent": 0.9}, 7, "AugurPact", tags = ["pistol"]),



        
        

    ]