from testingGrounds import Mod
MODS = [
        #-----------Empties-----------#
        Mod("EmptyMod", {}, 0, "EmptyMod", canBeDuplicated=True, tags=[]),
        #-----------------------------#

        #-----------Rifle Mods-----------#
        Mod("Serration", {"BonusDamagePercent": 0.15}, 4, "Serration"),
        Mod("Serration1", {"BonusDamagePercent": 0.3}, 5, "Serration"),
        Mod("Serration2", {"BonusDamagePercent": 0.45}, 6, "Serration"),
        Mod("Serration3", {"BonusDamagePercent": 0.6}, 7, "Serration"),
        Mod("Serration4", {"BonusDamagePercent": 0.75}, 8, "Serration"),
        Mod("Serration5", {"BonusDamagePercent": 0.9}, 9, "Serration"),
        Mod("Serration6", {"BonusDamagePercent": 1.05}, 10, "Serration"),
        Mod("Serration7", {"BonusDamagePercent": 1.2}, 11, "Serration"),
        Mod("Serration8", {"BonusDamagePercent": 1.35}, 12, "Serration"),
        Mod("Serration9", {"BonusDamagePercent": 1.5}, 13, "Serration"),
        Mod("Serration10", {"BonusDamagePercent": 1.65}, 14, "Serration"),

        Mod("CriticalDelay", {"BonusCritChance": 0.333, "BonusFireRate": -0.033}, 4, "CriticalDelay", ["PointStrike"]),
        Mod("CriticalDelay1", {"BonusCritChance": 0.667, "BonusFireRate": -0.067}, 5, "CriticalDelay", ["PointStrike"]),
        Mod("CriticalDelay2", {"BonusCritChance": 1, "BonusFireRate": -0.1}, 6, "CriticalDelay", ["PointStrike"]),
        Mod("CriticalDelay3", {"BonusCritChance": 1.333, "BonusFireRate": -0.133}, 7, "CriticalDelay", ["PointStrike"]),
        Mod("CriticalDelay4", {"BonusCritChance": 1.667, "BonusFireRate": -0.167}, 8, "CriticalDelay", ["PointStrike"]),
        Mod("CriticalDelay5", {"BonusCritChance": 2, "BonusFireRate": -0.2}, 9, "CriticalDelay", ["PointStrike"]),

        Mod("FastHands", {"BonusReload": -0.05}, 2, "FastHands"),
        Mod("FastHands1", {"BonusReload": -0.1}, 3, "FastHands"),
        Mod("FastHands2", {"BonusReload": -0.15}, 4, "FastHands"),
        Mod("FastHands3", {"BonusReload": -0.2}, 5, "FastHands"),
        Mod("FastHands4", {"BonusReload": -0.25}, 6, "FastHands"),
        Mod("FastHands5", {"BonusReload": -0.3}, 7, "FastHands"),

        Mod("Hellfire", {"BonusHeat": 0.15}, 6, "Hellfire"),
        Mod("Hellfire1", {"BonusHeat": 0.3}, 7, "Hellfire"),
        Mod("Hellfire2", {"BonusHeat": 0.45}, 8, "Hellfire"),
        Mod("Hellfire3", {"BonusHeat": 0.6}, 9, "Hellfire"),
        Mod("Hellfire4", {"BonusHeat": 0.75}, 10, "Hellfire"),
        Mod("Hellfire5", {"BonusHeat": 0.9}, 11, "Hellfire"),

        Mod("InfectedClip", {"BonusToxin": 0.15}, 6, "InfectedClip"),
        Mod("InfectedClip1", {"BonusToxin": 0.3}, 7, "InfectedClip"),
        Mod("InfectedClip2", {"BonusToxin": 0.45}, 8, "InfectedClip"),
        Mod("InfectedClip3", {"BonusToxin": 0.6}, 9, "InfectedClip"),
        Mod("InfectedClip4", {"BonusToxin": 0.75}, 10, "InfectedClip"),
        Mod("InfectedClip5", {"BonusToxin": 0.9}, 11, "InfectedClip"),

        Mod("MagazineWarp", {"BonusMagazine": 0.05}, 4, "MagazineWarp"),
        Mod("MagazineWarp1", {"BonusMagazine": 0.1}, 5, "MagazineWarp"),
        Mod("MagazineWarp2", {"BonusMagazine": 0.15}, 6, "MagazineWarp"),
        Mod("MagazineWarp3", {"BonusMagazine": 0.2}, 7, "MagazineWarp"),
        Mod("MagazineWarp4", {"BonusMagazine": 0.25}, 8, "MagazineWarp"),
        Mod("MagazineWarp5", {"BonusMagazine": 0.3}, 9, "MagazineWarp"),

        Mod("Stormbringer", {"BonusElectricity": 0.15}, 6, "Stormbringer"),
        Mod("Stormbringer1", {"BonusElectricity": 0.3}, 7, "Stormbringer"),
        Mod("Stormbringer2", {"BonusElectricity": 0.45}, 8, "Stormbringer"),
        Mod("Stormbringer3", {"BonusElectricity": 0.6}, 9, "Stormbringer"),
        Mod("Stormbringer4", {"BonusElectricity": 0.75}, 10, "Stormbringer"),
        Mod("Stormbringer5", {"BonusElectricity": 0.9}, 11, "Stormbringer"),

        Mod("CryoRounds", {"BonusCold": 0.15}, 6, "CryoRounds", "PrimedCryoRounds"),
        Mod("CryoRounds1", {"BonusCold": 0.3}, 7, "CryoRounds", "PrimedCryoRounds"),
        Mod("CryoRounds2", {"BonusCold": 0.45}, 8, "CryoRounds", "PrimedCryoRounds"),
        Mod("CryoRounds3", {"BonusCold": 0.6}, 9, "CryoRounds", "PrimedCryoRounds"),
        Mod("CryoRounds4", {"BonusCold": 0.75}, 10, "CryoRounds", "PrimedCryoRounds"),
        Mod("CryoRounds5", {"BonusCold": 0.9}, 11, "CryoRounds", "PrimedCryoRounds"),

        Mod("TaintedMag", {"BonusReload": -0.03, "BonusMagazine": 0.06}, 4, "TaintedMag"),
        Mod("TaintedMag1", {"BonusReload": -0.06, "BonusMagazine": 0.12}, 5, "TaintedMag"),
        Mod("TaintedMag2", {"BonusReload": -0.09, "BonusMagazine": 0.18}, 6, "TaintedMag"),
        Mod("TaintedMag3", {"BonusReload": -0.12, "BonusMagazine": 0.24}, 7, "TaintedMag"),
        Mod("TaintedMag4", {"BonusReload": -0.15, "BonusMagazine": 0.3}, 8, "TaintedMag"),
        Mod("TaintedMag5", {"BonusReload": -0.18, "BonusMagazine": 0.36}, 9, "TaintedMag"),
        Mod("TaintedMag6", {"BonusReload": -0.21, "BonusMagazine": 0.42}, 10, "TaintedMag"),
        Mod("TaintedMag7", {"BonusReload": -0.24, "BonusMagazine": 0.48}, 11, "TaintedMag"),
        Mod("TaintedMag8", {"BonusReload": -0.27, "BonusMagazine": 0.54}, 12, "TaintedMag"),
        Mod("TaintedMag9", {"BonusReload": -0.3, "BonusMagazine": 0.6}, 13, "TaintedMag"),
        Mod("TaintedMag10", {"BonusReload": -0.33, "BonusMagazine": 0.66}, 14, "TaintedMag"),

        Mod("PrimedCryoRounds", {"BonusCold": 0.15}, 6, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds1", {"BonusCold": 0.3}, 7, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds2", {"BonusCold": 0.45}, 8, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds3", {"BonusCold": 0.6}, 9, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds4", {"BonusCold": 0.75}, 10, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds5", {"BonusCold": 0.9}, 11, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds6", {"BonusCold": 1.05}, 12, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds7", {"BonusCold": 1.2}, 13, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds8", {"BonusCold": 1.35}, 14, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds9", {"BonusCold": 1.5}, 15, "PrimedCryoRounds", ["CryoRounds"]),
        Mod("PrimedCryoRounds10", {"BonusCold": 1.65}, 16, "PrimedCryoRounds", ["CryoRounds"]),

        Mod("RifleAmplitude", {"BonusStatusChance": 0.15}, 4, "RifleAmplitude"),
        Mod("RifleAmplitude1", {"BonusStatusChance": 0.3}, 5, "RifleAmplitude"),
        Mod("RifleAmplitude2", {"BonusStatusChance": 0.45}, 6, "RifleAmplitude"),
        Mod("RifleAmplitude3", {"BonusStatusChance": 0.6}, 7, "RifleAmplitude"),
        Mod("RifleAmplitude4", {"BonusStatusChance": 0.75}, 8, "RifleAmplitude"),
        Mod("RifleAmplitude5", {"BonusStatusChance": 0.9}, 9, "RifleAmplitude"),

        Mod("HeavyCaliber", {"BonusDamagePercent": 0.15}, 6, "HeavyCaliber"),
        Mod("HeavyCaliber1", {"BonusDamagePercent": 0.3}, 7, "HeavyCaliber"),
        Mod("HeavyCaliber2", {"BonusDamagePercent": 0.45}, 8, "HeavyCaliber"),
        Mod("HeavyCaliber3", {"BonusDamagePercent": 0.6}, 9, "HeavyCaliber"),
        Mod("HeavyCaliber4", {"BonusDamagePercent": 0.75}, 10, "HeavyCaliber"),
        Mod("HeavyCaliber5", {"BonusDamagePercent": 0.9}, 11, "HeavyCaliber"),
        Mod("HeavyCaliber6", {"BonusDamagePercent": 1.05}, 12, "HeavyCaliber"),
        Mod("HeavyCaliber7", {"BonusDamagePercent": 1.2}, 13, "HeavyCaliber"),
        Mod("HeavyCaliber8", {"BonusDamagePercent": 1.35}, 14, "HeavyCaliber"),
        Mod("HeavyCaliber9", {"BonusDamagePercent": 1.5}, 15, "HeavyCaliber"),
        Mod("HeavyCaliber10", {"BonusDamagePercent": 1.65}, 16, "HeavyCaliber"),

        Mod("MalignantForce", {"BonusToxin": 0.15, "BonusStatusChance": 0.15}, 4, "MalignantForce"),
        Mod("MalignantForce1", {"BonusToxin": 0.3, "BonusStatusChance": 0.3}, 5, "MalignantForce"),
        Mod("MalignantForce2", {"BonusToxin": 0.45, "BonusStatusChance": 0.45}, 6, "MalignantForce"),
        Mod("MalignantForce3", {"BonusToxin": 0.6, "BonusStatusChance": 0.6}, 7, "MalignantForce"),

        Mod("PointStrike", {"BonusCritChance": 0.25}, 4, "PointStrike", ["CriticalDelay"]),
        Mod("PointStrike1", {"BonusCritChance": 0.5}, 5, "PointStrike", ["CriticalDelay"]),
        Mod("PointStrike2", {"BonusCritChance": 0.75}, 6, "PointStrike", ["CriticalDelay"]),
        Mod("PointStrike3", {"BonusCritChance": 1}, 7, "PointStrike", ["CriticalDelay"]),
        Mod("PointStrike4", {"BonusCritChance": 1.25}, 8, "PointStrike", ["CriticalDelay"]),
        Mod("PointStrike5", {"BonusCritChance": 1.5}, 9, "PointStrike", ["CriticalDelay"]),

        Mod("SpeedTrigger", {"BonusFireRate": 0.10}, 4, "SpeedTrigger"),
        Mod("SpeedTrigger1", {"BonusFireRate": 0.20}, 5, "SpeedTrigger"),
        Mod("SpeedTrigger2", {"BonusFireRate": 0.30}, 6, "SpeedTrigger"),
        Mod("SpeedTrigger3", {"BonusFireRate": 0.40}, 7, "SpeedTrigger"),
        Mod("SpeedTrigger4", {"BonusFireRate": 0.50}, 8, "SpeedTrigger"),
        Mod("SpeedTrigger5", {"BonusFireRate": 0.60}, 9, "SpeedTrigger"),

        Mod("SplitChamber", {"BonusMultishot": 0.15}, 10, "SplitChamber"),
        Mod("SplitChamber1", {"BonusMultishot": 0.3}, 11, "SplitChamber"),
        Mod("SplitChamber2", {"BonusMultishot": 0.45}, 12, "SplitChamber"),
        Mod("SplitChamber3", {"BonusMultishot": 0.6}, 13, "SplitChamber"),
        Mod("SplitChamber4", {"BonusMultishot": 0.75}, 14, "SplitChamber"),
        Mod("SplitChamber5", {"BonusMultishot": 0.9}, 15, "SplitChamber"),

        Mod("VitalSense", {"BonusCritMultiplier": 0.20}, 4, "VitalSense"),
        Mod("VitalSense1", {"BonusCritMultiplier": 0.40}, 5, "VitalSense"),
        Mod("VitalSense2", {"BonusCritMultiplier": 0.60}, 6, "VitalSense"),
        Mod("VitalSense3", {"BonusCritMultiplier": 0.80}, 7, "VitalSense"),
        Mod("VitalSense4", {"BonusCritMultiplier": 1.00}, 8, "VitalSense"),
        Mod("VitalSense5", {"BonusCritMultiplier": 1.20}, 9, "VitalSense"),

        Mod("Wildfire", {"BonusHeat": 0.15, "BonusMagazine": 0.05}, 6, "Wildfire"),
        Mod("Wildfire1", {"BonusHeat": 0.3, "BonusMagazine": 0.1}, 7, "Wildfire"),
        Mod("Wildfire2", {"BonusHeat": 0.45, "BonusMagazine": 0.15}, 8, "Wildfire"),
        Mod("Wildfire3", {"BonusHeat": 0.6, "BonusMagazine": 0.2}, 9, "Wildfire"),

        Mod("PiercingHit", {"BonusPuncture": 0.15}, 4, "PiercingHit"),
        Mod("PiercingHit1", {"BonusPuncture": 0.3}, 5, "PiercingHit"),
        Mod("PiercingHit2", {"BonusPuncture": 0.45}, 6, "PiercingHit"),
        Mod("PiercingHit3", {"BonusPuncture": 0.6}, 7, "PiercingHit"),
        Mod("PiercingHit4", {"BonusPuncture": 0.75}, 8, "PiercingHit"),
        Mod("PiercingHit5", {"BonusPuncture": 0.9}, 9, "PiercingHit"),

        Mod("RifleAptitude", {"BonusStatusChance": 0.15}, 4, "RifleAptitude"),
        Mod("RifleAptitude1", {"BonusStatusChance": 0.3}, 5, "RifleAptitude"),
        Mod("RifleAptitude2", {"BonusStatusChance": 0.45}, 6, "RifleAptitude"),
        Mod("RifleAptitude3", {"BonusStatusChance": 0.6}, 7, "RifleAptitude"),
        Mod("RifleAptitude4", {"BonusStatusChance": 0.75}, 8, "RifleAptitude"),
        Mod("RifleAptitude5", {"BonusStatusChance": 0.9}, 9, "RifleAptitude"),

        Mod("SawtoothClip", {"BonusSlash": 0.15}, 4, "SawtoothClip"),
        Mod("SawtoothClip1", {"BonusSlash": 0.3}, 5, "SawtoothClip"),
        Mod("SawtoothClip2", {"BonusSlash": 0.45}, 6, "SawtoothClip"),
        Mod("SawtoothClip3", {"BonusSlash": 0.6}, 7, "SawtoothClip"),
        Mod("SawtoothClip4", {"BonusSlash": 0.75}, 8, "SawtoothClip"),
        Mod("SawtoothClip5", {"BonusSlash": 0.9}, 9, "SawtoothClip"),

        Mod("Rupture", {"BonusImpact": 0.15}, 4, "Rupture"),
        Mod("Rupture1", {"BonusImpact": 0.3}, 5, "Rupture"),
        Mod("Rupture2", {"BonusImpact": 0.45}, 6, "Rupture"),
        Mod("Rupture3", {"BonusImpact": 0.6}, 7, "Rupture"),
        Mod("Rupture4", {"BonusImpact": 0.75}, 8, "Rupture"),
        Mod("Rupture5", {"BonusImpact": 0.9}, 9, "Rupture"),

        Mod("CrashCourse", {"BonusImpact": 0.2}, 4, "CrashCourse"),
        Mod("CrashCourse1", {"BonusImpact": 0.4}, 5, "CrashCourse"),
        Mod("CrashCourse2", {"BonusImpact": 0.6}, 6, "CrashCourse"),
        Mod("CrashCourse3", {"BonusImpact": 0.8}, 7, "CrashCourse"),
        Mod("CrashCourse4", {"BonusImpact": 1}, 8, "CrashCourse"),
        Mod("CrashCourse5", {"BonusImpact": 1.2}, 9, "CrashCourse"),

        Mod("BaneOfCorpus", {"BonusToCorpus": 1.05}, 4, "BaneOfCorpus", ["PrimedBaneOfCorpus"]),
        Mod("BaneOfCorpus1", {"BonusToCorpus": 1.1}, 5, "BaneOfCorpus", ["PrimedBaneOfCorpus"]),
        Mod("BaneOfCorpus2", {"BonusToCorpus": 1.15}, 6, "BaneOfCorpus", ["PrimedBaneOfCorpus"]),
        Mod("BaneOfCorpus3", {"BonusToCorpus": 1.2}, 7, "BaneOfCorpus", ["PrimedBaneOfCorpus"]),
        Mod("BaneOfCorpus4", {"BonusToCorpus": 1.25}, 8, "BaneOfCorpus", ["PrimedBaneOfCorpus"]),
        Mod("BaneOfCorpus5", {"BonusToCorpus": 1.3}, 9, "BaneOfCorpus", ["PrimedBaneOfCorpus"]),

        Mod("BaneOfGrineer", {"BonusToGrineer": 1.05}, 4, "BaneOfGrineer", ["PrimedBaneOfGrineer"]),
        Mod("BaneOfGrineer1", {"BonusToGrineer": 1.1}, 5, "BaneOfGrineer", ["PrimedBaneOfGrineer"]),
        Mod("BaneOfGrineer2", {"BonusToGrineer": 1.15}, 6, "BaneOfGrineer", ["PrimedBaneOfGrineer"]),
        Mod("BaneOfGrineer3", {"BonusToGrineer": 1.2}, 7, "BaneOfGrineer", ["PrimedBaneOfGrineer"]),
        Mod("BaneOfGrineer4", {"BonusToGrineer": 1.25}, 8, "BaneOfGrineer", ["PrimedBaneOfGrineer"]),
        Mod("BaneOfGrineer5", {"BonusToGrineer": 1.3}, 9, "BaneOfGrineer", ["PrimedBaneOfGrineer"]),

        Mod("BaneOfInfested", {"BonusToInfested": 1.05}, 4, "BaneOfInfested", ["PrimedBaneOfInfested"]),
        Mod("BaneOfInfested1", {"BonusToInfested": 1.1}, 5, "BaneOfInfested", ["PrimedBaneOfInfested"]),
        Mod("BaneOfInfested2", {"BonusToInfested": 1.15}, 6, "BaneOfInfested", ["PrimedBaneOfInfested"]),
        Mod("BaneOfInfested3", {"BonusToInfested": 1.2}, 7, "BaneOfInfested", ["PrimedBaneOfInfested"]),
        Mod("BaneOfInfested4", {"BonusToInfested": 1.25}, 8, "BaneOfInfested", ["PrimedBaneOfInfested"]),
        Mod("BaneOfInfested5", {"BonusToInfested": 1.3}, 9, "BaneOfInfested", ["PrimedBaneOfInfested"]),

        Mod("BaneOfCorrupted", {"BonusToCorrupted": 1.05}, 4, "BaneOfCorrupted", ["PrimedBaneOfCorrupted"]),
        Mod("BaneOfCorrupted1", {"BonusToCorrupted": 1.1}, 5, "BaneOfCorrupted", ["PrimedBaneOfCorrupted"]),
        Mod("BaneOfCorrupted2", {"BonusToCorrupted": 1.15}, 6, "BaneOfCorrupted", ["PrimedBaneOfCorrupted"]),
        Mod("BaneOfCorrupted3", {"BonusToCorrupted": 1.2}, 7, "BaneOfCorrupted", ["PrimedBaneOfCorrupted"]),
        Mod("BaneOfCorrupted4", {"BonusToCorrupted": 1.25}, 8, "BaneOfCorrupted", ["PrimedBaneOfCorrupted"]),
        Mod("BaneOfCorrupted5", {"BonusToCorrupted": 1.3}, 9, "BaneOfCorrupted", ["PrimedBaneOfCorrupted"]),

        Mod("PrimedBaneOfCorpus", {"BonusToCorpus": 1.05}, 4, "PrimedBaneOfCorpus", ["BaneOfCorpus"]),
        Mod("PrimedBaneOfCorpus1", {"BonusToCorpus": 1.1}, 5, "PrimedBaneOfCorpus", ["BaneOfCorpus"]),
        Mod("PrimedBaneOfCorpus2", {"BonusToCorpus": 1.15}, 6, "PrimedBaneOfCorpus", ["BaneOfCorpus"]),
        Mod("PrimedBaneOfCorpus3", {"BonusToCorpus": 1.2}, 7, "PrimedBaneOfCorpus", ["BaneOfCorpus"]),
        Mod("PrimedBaneOfCorpus4", {"BonusToCorpus": 1.25}, 8, "PrimedBaneOfCorpus", ["BaneOfCorpus"]),
        Mod("PrimedBaneOfCorpus5", {"BonusToCorpus": 1.3}, 9, "PrimedBaneOfCorpus", ["BaneOfCorpus"]),
        Mod("PrimedBaneOfCorpus6", {"BonusToCorpus": 1.35}, 10, "PrimedBaneOfCorpus", ["BaneOfCorpus"]),
        Mod("PrimedBaneOfCorpus7", {"BonusToCorpus": 1.4}, 11, "PrimedBaneOfCorpus", ["BaneOfCorpus"]),
        Mod("PrimedBaneOfCorpus8", {"BonusToCorpus": 1.45}, 12, "PrimedBaneOfCorpus", ["BaneOfCorpus"]),
        Mod("PrimedBaneOfCorpus9", {"BonusToCorpus": 1.5}, 13, "PrimedBaneOfCorpus", ["BaneOfCorpus"]),
        Mod("PrimedBaneOfCorpus10", {"BonusToCorpus": 1.55}, 14, "PrimedBaneOfCorpus", ["BaneOfCorpus"]),

        Mod("PrimedBaneOfGrineer", {"BonusToGrineer": 1.05}, 4, "PrimedBaneOfGrineer", ["BaneOfGrineer"]),
        Mod("PrimedBaneOfGrineer1", {"BonusToGrineer": 1.1}, 5, "PrimedBaneOfGrineer", ["BaneOfGrineer"]),
        Mod("PrimedBaneOfGrineer2", {"BonusToGrineer": 1.15}, 6, "PrimedBaneOfGrineer", ["BaneOfGrineer"]),
        Mod("PrimedBaneOfGrineer3", {"BonusToGrineer": 1.2}, 7, "PrimedBaneOfGrineer", ["BaneOfGrineer"]),
        Mod("PrimedBaneOfGrineer4", {"BonusToGrineer": 1.25}, 8, "PrimedBaneOfGrineer", ["BaneOfGrineer"]),
        Mod("PrimedBaneOfGrineer5", {"BonusToGrineer": 1.3}, 9, "PrimedBaneOfGrineer", ["BaneOfGrineer"]),
        Mod("PrimedBaneOfGrineer6", {"BonusToGrineer": 1.35}, 10, "PrimedBaneOfGrineer", ["BaneOfGrineer"]),
        Mod("PrimedBaneOfGrineer7", {"BonusToGrineer": 1.4}, 11, "PrimedBaneOfGrineer", ["BaneOfGrineer"]),
        Mod("PrimedBaneOfGrineer8", {"BonusToGrineer": 1.45}, 12, "PrimedBaneOfGrineer", ["BaneOfGrineer"]),
        Mod("PrimedBaneOfGrineer9", {"BonusToGrineer": 1.5}, 13, "PrimedBaneOfGrineer", ["BaneOfGrineer"]),
        Mod("PrimedBaneOfGrineer10", {"BonusToGrineer": 1.55}, 14, "PrimedBaneOfGrineer", ["BaneOfGrineer"]),

        Mod("PrimedBaneOfInfested", {"BonusToInfested": 1.05}, 4, "PrimedBaneOfInfested", ["BaneOfInfested"]),
        Mod("PrimedBaneOfInfested1", {"BonusToInfested": 1.1}, 5, "PrimedBaneOfInfested", ["BaneOfInfested"]),
        Mod("PrimedBaneOfInfested2", {"BonusToInfested": 1.15}, 6, "PrimedBaneOfInfested", ["BaneOfInfested"]),
        Mod("PrimedBaneOfInfested3", {"BonusToInfested": 1.2}, 7, "PrimedBaneOfInfested", ["BaneOfInfested"]),
        Mod("PrimedBaneOfInfested4", {"BonusToInfested": 1.25}, 8, "PrimedBaneOfInfested", ["BaneOfInfested"]),
        Mod("PrimedBaneOfInfested5", {"BonusToInfested": 1.3}, 9, "PrimedBaneOfInfested", ["BaneOfInfested"]),
        Mod("PrimedBaneOfInfested6", {"BonusToInfested": 1.35}, 10, "PrimedBaneOfInfested", ["BaneOfInfested"]),
        Mod("PrimedBaneOfInfested7", {"BonusToInfested": 1.4}, 11, "PrimedBaneOfInfested", ["BaneOfInfested"]),
        Mod("PrimedBaneOfInfested8", {"BonusToInfested": 1.45}, 12, "PrimedBaneOfInfested", ["BaneOfInfested"]),
        Mod("PrimedBaneOfInfested9", {"BonusToInfested": 1.5}, 13, "PrimedBaneOfInfested", ["BaneOfInfested"]),
        Mod("PrimedBaneOfInfested10", {"BonusToInfested": 1.55}, 14, "PrimedBaneOfInfested", ["BaneOfInfested"]),

        Mod("PrimedBaneOfCorrupted", {"BonusToCorrupted": 1.05}, 4, "PrimedBaneOfCorrupted", ["BaneOfCorrupted"]),
        Mod("PrimedBaneOfCorrupted1", {"BonusToCorrupted": 1.1}, 5, "PrimedBaneOfCorrupted", ["BaneOfCorrupted"]),
        Mod("PrimedBaneOfCorrupted2", {"BonusToCorrupted": 1.15}, 6, "PrimedBaneOfCorrupted", ["BaneOfCorrupted"]),
        Mod("PrimedBaneOfCorrupted3", {"BonusToCorrupted": 1.2}, 7, "PrimedBaneOfCorrupted", ["BaneOfCorrupted"]),
        Mod("PrimedBaneOfCorrupted4", {"BonusToCorrupted": 1.25}, 8, "PrimedBaneOfCorrupted", ["BaneOfCorrupted"]),
        Mod("PrimedBaneOfCorrupted5", {"BonusToCorrupted": 1.3}, 9, "PrimedBaneOfCorrupted", ["BaneOfCorrupted"]),
        Mod("PrimedBaneOfCorrupted6", {"BonusToCorrupted": 1.35}, 10, "PrimedBaneOfCorrupted", ["BaneOfCorrupted"]),
        Mod("PrimedBaneOfCorrupted7", {"BonusToCorrupted": 1.4}, 11, "PrimedBaneOfCorrupted", ["BaneOfCorrupted"]),
        Mod("PrimedBaneOfCorrupted8", {"BonusToCorrupted": 1.45}, 12, "PrimedBaneOfCorrupted", ["BaneOfCorrupted"]),
        Mod("PrimedBaneOfCorrupted9", {"BonusToCorrupted": 1.5}, 13, "PrimedBaneOfCorrupted", ["BaneOfCorrupted"]),
        Mod("PrimedBaneOfCorrupted10", {"BonusToCorrupted": 1.55}, 14, "PrimedBaneOfCorrupted", ["BaneOfCorrupted"]),
        #-----------------------------#


        #-----------Pistol Mods-----------#
        Mod("HornetStrike", {"BonusDamagePercent": 0.2}, 4, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike1", {"BonusDamagePercent": 0.4}, 5, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike2", {"BonusDamagePercent": 0.6}, 6, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike3", {"BonusDamagePercent": 0.8}, 7, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike4", {"BonusDamagePercent": 1}, 8, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike5", {"BonusDamagePercent": 1.2}, 9, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike6", {"BonusDamagePercent": 1.4}, 10, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike7", {"BonusDamagePercent": 1.6}, 11, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike8", {"BonusDamagePercent": 1.8}, 12, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike9", {"BonusDamagePercent": 2}, 13, "HornetStrike", tags = ["pistol"]),
        Mod("HornetStrike10", {"BonusDamagePercent": 2.2}, 14, "HornetStrike", tags = ["pistol"]),

        Mod("BarrelDiffusion", {"BonusMultishot": 0.2}, 6, "BarrelDiffusion", tags = ["pistol"]),
        Mod("BarrelDiffusion1", {"BonusMultishot": 0.4}, 7, "BarrelDiffusion", tags = ["pistol"]),
        Mod("BarrelDiffusion2", {"BonusMultishot": 0.6}, 8, "BarrelDiffusion", tags = ["pistol"]),
        Mod("BarrelDiffusion3", {"BonusMultishot": 0.8}, 9, "BarrelDiffusion", tags = ["pistol"]),
        Mod("BarrelDiffusion4", {"BonusMultishot": 1}, 10, "BarrelDiffusion", tags = ["pistol"]),
        Mod("BarrelDiffusion5", {"BonusMultishot": 1.2}, 11, "BarrelDiffusion", tags = ["pistol"]),

        Mod("Convulsion", {"BonusElectricity": 0.15}, 6, "Convulsion", tags = ["pistol"]),
        Mod("Convulsion1", {"BonusElectricity": 0.3}, 7, "Convulsion", tags = ["pistol"]),
        Mod("Convulsion2", {"BonusElectricity": 0.45}, 8, "Convulsion", tags = ["pistol"]),
        Mod("Convulsion3", {"BonusElectricity": 0.6}, 9, "Convulsion", tags = ["pistol"]),
        Mod("Convulsion4", {"BonusElectricity": 0.75}, 10, "Convulsion", tags = ["pistol"]),
        Mod("Convulsion5", {"BonusElectricity": 0.9}, 11, "Convulsion", tags = ["pistol"]),

        Mod("HeatedCharge", {"BonusHeat": 0.15}, 6, "HeatedCharge", tags = ["pistol"]),
        Mod("HeatedCharge1", {"BonusHeat": 0.3}, 7, "HeatedCharge", tags = ["pistol"]),
        Mod("HeatedCharge2", {"BonusHeat": 0.45}, 8, "HeatedCharge", tags = ["pistol"]),
        Mod("HeatedCharge3", {"BonusHeat": 0.6}, 9, "HeatedCharge", tags = ["pistol"]),
        Mod("HeatedCharge4", {"BonusHeat": 0.75}, 10, "HeatedCharge", tags = ["pistol"]),
        Mod("HeatedCharge5", {"BonusHeat": 0.9}, 11, "HeatedCharge", tags = ["pistol"]),

        Mod("PathogenRounds", {"BonusToxin": 0.15}, 6, "PathogenRounds", tags = ["pistol"]),
        Mod("PathogenRounds1", {"BonusToxin": 0.3}, 7, "PathogenRounds", tags = ["pistol"]),
        Mod("PathogenRounds2", {"BonusToxin": 0.45}, 8, "PathogenRounds", tags = ["pistol"]),
        Mod("PathogenRounds3", {"BonusToxin": 0.6}, 9, "PathogenRounds", tags = ["pistol"]),
        Mod("PathogenRounds4", {"BonusToxin": 0.75}, 10, "PathogenRounds", tags = ["pistol"]),
        Mod("PathogenRounds5", {"BonusToxin": 0.9}, 11, "PathogenRounds", tags = ["pistol"]),
        
        Mod("Gunslinger", {"BonusFireRate": 0.12}, 4, "Gunslinger", tags = ["pistol"]),
        Mod("Gunslinger1", {"BonusFireRate": 0.24}, 5, "Gunslinger", tags = ["pistol"]),
        Mod("Gunslinger2", {"BonusFireRate": 0.36}, 6, "Gunslinger", tags = ["pistol"]),
        Mod("Gunslinger3", {"BonusFireRate": 0.48}, 7, "Gunslinger", tags = ["pistol"]),
        Mod("Gunslinger4", {"BonusFireRate": 0.6}, 8, "Gunslinger", tags = ["pistol"]),
        Mod("Gunslinger5", {"BonusFireRate": 0.72}, 9, "Gunslinger", tags = ["pistol"]),

        Mod("PistolGambit", {"BonusCritChance" : 0.2}, 4, "PistolGambit", tags = ["pistol"]),
        Mod("PistolGambit1", {"BonusCritChance" : 0.4}, 5, "PistolGambit", tags = ["pistol"]),
        Mod("PistolGambit2", {"BonusCritChance" : 0.6}, 6, "PistolGambit", tags = ["pistol"]),
        Mod("PistolGambit3", {"BonusCritChance" : 0.8}, 7, "PistolGambit", tags = ["pistol"]),
        Mod("PistolGambit4", {"BonusCritChance" : 1}, 8, "PistolGambit", tags = ["pistol"]),
        Mod("PistolGambit5", {"BonusCritChance" : 1.2}, 9, "PistolGambit", tags = ["pistol"]),

        Mod("SlipMagazine", {"BonusMagazine": 0.05}, 4, "SlipMagazine", tags = ["pistol"]),
        Mod("SlipMagazine1", {"BonusMagazine": 0.1}, 5, "SlipMagazine", tags = ["pistol"]),
        Mod("SlipMagazine2", {"BonusMagazine": 0.15}, 6, "SlipMagazine", tags = ["pistol"]),
        Mod("SlipMagazine3", {"BonusMagazine": 0.2}, 7, "SlipMagazine", tags = ["pistol"]),
        Mod("SlipMagazine4", {"BonusMagazine": 0.25}, 8, "SlipMagazine", tags = ["pistol"]),
        Mod("SlipMagazine5", {"BonusMagazine": 0.3}, 9, "SlipMagazine", tags = ["pistol"]),

        Mod("TargetCracker", {"BonusCritMultiplier": 0.1}, 4, "TargetCracker", tags = ["pistol"], conflicts=["PrimedTargetCracker"]),
        Mod("TargetCracker1", {"BonusCritMultiplier": 0.2}, 5, "TargetCracker", tags = ["pistol"], conflicts=["PrimedTargetCracker"]),
        Mod("TargetCracker2", {"BonusCritMultiplier": 0.3}, 6, "TargetCracker", tags = ["pistol"], conflicts=["PrimedTargetCracker"]),
        Mod("TargetCracker3", {"BonusCritMultiplier": 0.4}, 7, "TargetCracker", tags = ["pistol"], conflicts=["PrimedTargetCracker"]),
        Mod("TargetCracker4", {"BonusCritMultiplier": 0.5}, 8, "TargetCracker", tags = ["pistol"], conflicts=["PrimedTargetCracker"]),
        Mod("TargetCracker5", {"BonusCritMultiplier": 0.6}, 9, "TargetCracker", tags = ["pistol"], conflicts=["PrimedTargetCracker"]),

        Mod("ConcussionRounds", {"BonusImpact": 0.15}, 2, "ConcussionRounds", tags = ["pistol"]),
        Mod("ConcussionRounds1", {"BonusImpact": 0.3}, 3, "ConcussionRounds", tags = ["pistol"]),
        Mod("ConcussionRounds2", {"BonusImpact": 0.45}, 4, "ConcussionRounds", tags = ["pistol"]),
        Mod("ConcussionRounds3", {"BonusImpact": 0.6}, 5, "ConcussionRounds", tags = ["pistol"]),
        Mod("ConcussionRounds4", {"BonusImpact": 0.75}, 6, "ConcussionRounds", tags = ["pistol"]),
        Mod("ConcussionRounds5", {"BonusImpact": 0.9}, 7, "ConcussionRounds", tags = ["pistol"]),

        Mod("Quickdraw", {"BonusReload": 0.08}, 2, "Quickdraw", tags = ["pistol"]),
        Mod("Quickdraw1", {"BonusReload": 0.16}, 3, "Quickdraw", tags = ["pistol"]),
        Mod("Quickdraw2", {"BonusReload": 0.24}, 4, "Quickdraw", tags = ["pistol"]),
        Mod("Quickdraw3", {"BonusReload": 0.32}, 5, "Quickdraw", tags = ["pistol"]),
        Mod("Quickdraw4", {"BonusReload": 0.4}, 6, "Quickdraw", tags = ["pistol"]),
        Mod("Quickdraw5", {"BonusReload": 0.48}, 7, "Quickdraw", tags = ["pistol"]),

        Mod("RazorShot", {"BonusSlash": 0.15}, 2, "RazorShot", tags = ["pistol"]),
        Mod("RazorShot1", {"BonusSlash": 0.3}, 3, "RazorShot", tags = ["pistol"]),
        Mod("RazorShot2", {"BonusSlash": 0.45}, 4, "RazorShot", tags = ["pistol"]),
        Mod("RazorShot3", {"BonusSlash": 0.6}, 5, "RazorShot", tags = ["pistol"]),
        Mod("RazorShot4", {"BonusSlash": 0.75}, 6, "RazorShot", tags = ["pistol"]),
        Mod("RazorShot5", {"BonusSlash": 0.9}, 7, "RazorShot", tags = ["pistol"]),

        Mod("SureShot", {"BonusStatusChance": 0.15}, 2, "SureShot", tags = ["pistol"]),
        Mod("SureShot1", {"BonusStatusChance": 0.3}, 3, "SureShot", tags = ["pistol"]),
        Mod("SureShot2", {"BonusStatusChance": 0.45}, 4, "SureShot", tags = ["pistol"]),
        Mod("SureShot3", {"BonusStatusChance": 0.6}, 5, "SureShot", tags = ["pistol"]),
        Mod("SureShot4", {"BonusStatusChance": 0.75}, 6, "SureShot", tags = ["pistol"]),
        Mod("SureShot5", {"BonusStatusChance": 0.9}, 7, "SureShot", tags = ["pistol"]),

        Mod("DeepFreeze", {"BonusCold": 0.15}, 6, "DeepFreeze", tags = ["pistol"]),
        Mod("DeepFreeze1", {"BonusCold": 0.3}, 7, "DeepFreeze", tags = ["pistol"]),
        Mod("DeepFreeze2", {"BonusCold": 0.45}, 8, "DeepFreeze", tags = ["pistol"]),
        Mod("DeepFreeze3", {"BonusCold": 0.6}, 9, "DeepFreeze", tags = ["pistol"]),
        Mod("DeepFreeze4", {"BonusCold": 0.75}, 10, "DeepFreeze", tags = ["pistol"]),
        Mod("DeepFreeze5", {"BonusCold": 0.9}, 11, "DeepFreeze", tags = ["pistol"]),

        Mod("StunningSpeed", {"BonusReloadSpeed": 0.1, "BonusStatusChance": 0.075}, 6, "StunningSpeed", tags = ["pistol"]),
        Mod("StunningSpeed1", {"BonusReloadSpeed": 0.2, "BonusStatusChance": 0.15}, 7, "StunningSpeed", tags = ["pistol"]),
        Mod("StunningSpeed2", {"BonusReloadSpeed": 0.3, "BonusStatusChance": 0.225}, 8, "StunningSpeed", tags = ["pistol"]),
        Mod("StunningSpeed3", {"BonusReloadSpeed": 0.4, "BonusStatusChance": 0.3}, 9, "StunningSpeed", tags = ["pistol"]),

        Mod("AnemicAgility", {"BonusFireRate": 0.15, "BonusDamage": -0.025}, 4, "AnemicAgility", tags = ["pistol"]),
        Mod("AnemicAgility1", {"BonusFireRate": 0.3, "BonusDamage": -0.05}, 5, "AnemicAgility", tags = ["pistol"]),
        Mod("AnemicAgility2", {"BonusFireRate": 0.45, "BonusDamage": -0.075}, 6, "AnemicAgility", tags = ["pistol"]),
        Mod("AnemicAgility3", {"BonusFireRate": 0.6, "BonusDamage": -0.1}, 7, "AnemicAgility", tags = ["pistol"]),
        Mod("AnemicAgility4", {"BonusFireRate": 0.75, "BonusDamage": -0.125}, 8, "AnemicAgility", tags = ["pistol"]),
        Mod("AnemicAgility5", {"BonusFireRate": 0.9, "BonusDamage": -0.15}, 9, "AnemicAgility", tags = ["pistol"]),

        Mod("HollowPoint", {"BonusDamage": -0.025, "BonusCritMultiplier": 0.1}, 4, "HollowPoint", tags = ["pistol"]),
        Mod("HollowPoint1", {"BonusDamage": -0.05, "BonusCritMultiplier": 0.2}, 5, "HollowPoint", tags = ["pistol"]),
        Mod("HollowPoint2", {"BonusDamage": -0.075, "BonusCritMultiplier": 0.3}, 6, "HollowPoint", tags = ["pistol"]),
        Mod("HollowPoint3", {"BonusDamage": -0.1, "BonusCritMultiplier": 0.4}, 7, "HollowPoint", tags = ["pistol"]),
        Mod("HollowPoint4", {"BonusDamage": -0.125, "BonusCritMultiplier": 0.5}, 8, "HollowPoint", tags = ["pistol"]),
        Mod("HollowPoint5", {"BonusDamage": -0.15, "BonusCritMultiplier": 0.6}, 9, "HollowPoint", tags = ["pistol"]),

        Mod("NoReturn", {"BonusPuncture": 0.15}, 2, "NoReturn", tags = ["pistol"]),
        Mod("NoReturn1", {"BonusPuncture": 0.3}, 3, "NoReturn", tags = ["pistol"]),
        Mod("NoReturn2", {"BonusPuncture": 0.45}, 4, "NoReturn", tags = ["pistol"]),
        Mod("NoReturn3", {"BonusPuncture": 0.6}, 5, "NoReturn", tags = ["pistol"]),
        Mod("NoReturn4", {"BonusPuncture": 0.75}, 6, "NoReturn", tags = ["pistol"]),
        Mod("NoReturn5", {"BonusPuncture": 0.9}, 7, "NoReturn", tags = ["pistol"]),

        Mod("PistolPestilence", {"BonusToxin": 0.15, "BonusStatusChance": 0.15}, 4, "PistolPestilence", tags = ["pistol"]),
        Mod("PistolPestilence1", {"BonusToxin": 0.3, "BonusStatusChance": 0.3}, 5, "PistolPestilence", tags = ["pistol"]),
        Mod("PistolPestilence2", {"BonusToxin": 0.45, "BonusStatusChance": 0.45}, 6, "PistolPestilence", tags = ["pistol"]),
        Mod("PistolPestilence3", {"BonusToxin": 0.6, "BonusStatusChance": 0.6}, 7, "PistolPestilence", tags = ["pistol"]),

        Mod("PrimedTargetCracker", {"BonusCritMultiplier": 0.1}, 4, "PrimedTargetCracker", tags = ["pistol"], conflicts=["TargetCracker"]),
        Mod("PrimedTargetCracker1", {"BonusCritMultiplier": 0.2}, 5, "PrimedTargetCracker", tags = ["pistol"], conflicts=["TargetCracker"]),
        Mod("PrimedTargetCracker2", {"BonusCritMultiplier": 0.3}, 6, "PrimedTargetCracker", tags = ["pistol"], conflicts=["TargetCracker"]),
        Mod("PrimedTargetCracker3", {"BonusCritMultiplier": 0.4}, 7, "PrimedTargetCracker", tags = ["pistol"], conflicts=["TargetCracker"]),
        Mod("PrimedTargetCracker4", {"BonusCritMultiplier": 0.5}, 8, "PrimedTargetCracker", tags = ["pistol"], conflicts=["TargetCracker"]),
        Mod("PrimedTargetCracker5", {"BonusCritMultiplier": 0.6}, 9, "PrimedTargetCracker", tags = ["pistol"], conflicts=["TargetCracker"]),
        Mod("PrimedTargetCracker6", {"BonusCritMultiplier": 0.7}, 10, "PrimedTargetCracker", tags = ["pistol"], conflicts=["TargetCracker"]),
        Mod("PrimedTargetCracker7", {"BonusCritMultiplier": 0.8}, 11, "PrimedTargetCracker", tags = ["pistol"], conflicts=["TargetCracker"]),
        Mod("PrimedTargetCracker8", {"BonusCritMultiplier": 0.9}, 12, "PrimedTargetCracker", tags = ["pistol"], conflicts=["TargetCracker"]),
        Mod("PrimedTargetCracker9", {"BonusCritMultiplier": 1}, 13, "PrimedTargetCracker", tags = ["pistol"], conflicts=["TargetCracker"]),
        Mod("PrimedTargetCracker10", {"BonusCritMultiplier": 1.1}, 14, "PrimedTargetCracker", tags = ["pistol"], conflicts=["TargetCracker"]),

        Mod("AugurPact", {"BonusDamagePercent": 0.15}, 2, "AugurPact", tags = ["pistol"]),
        Mod("AugurPact1", {"BonusDamagePercent": 0.3}, 3, "AugurPact", tags = ["pistol"]),
        Mod("AugurPact2", {"BonusDamagePercent": 0.45}, 4, "AugurPact", tags = ["pistol"]),
        Mod("AugurPact3", {"BonusDamagePercent": 0.6}, 5, "AugurPact", tags = ["pistol"]),
        Mod("AugurPact4", {"BonusDamagePercent": 0.75}, 6, "AugurPact", tags = ["pistol"]),
        Mod("AugurPact5", {"BonusDamagePercent": 0.9}, 7, "AugurPact", tags = ["pistol"]),
        #-----------------------------#


        #-----------Shotgun Mods-----------#
        Mod("HellsChamber", {"BonusMultishot": 0.15}, 10, "HellsChamber", tags = ["shotgun"]),
        Mod("HellsChamber1", {"BonusMultishot": 0.3}, 11, "HellsChamber", tags = ["shotgun"]),
        Mod("HellsChamber2", {"BonusMultishot": 0.45}, 12, "HellsChamber", tags = ["shotgun"]),
        Mod("HellsChamber3", {"BonusMultishot": 0.6}, 13, "HellsChamber", tags = ["shotgun"]),
        Mod("HellsChamber4", {"BonusMultishot": 0.75}, 14, "HellsChamber", tags = ["shotgun"]),
        Mod("HellsChamber5", {"BonusMultishot": 0.9}, 15, "HellsChamber", tags = ["shotgun"]),

        Mod("PrimedPointBlank", {"BonusDamagePercent": 0.15}, 4, "PrimedPointBlank", tags = ["shotgun"], conflicts=["PointBlank"]),
        Mod("PrimedPointBlank1", {"BonusDamagePercent": 0.3}, 5, "PrimedPointBlank", tags = ["shotgun"], conflicts=["PointBlank"]),
        Mod("PrimedPointBlank2", {"BonusDamagePercent": 0.45}, 6, "PrimedPointBlank", tags = ["shotgun"], conflicts=["PointBlank"]),
        Mod("PrimedPointBlank3", {"BonusDamagePercent": 0.6}, 7, "PrimedPointBlank", tags = ["shotgun"], conflicts=["PointBlank"]),
        Mod("PrimedPointBlank4", {"BonusDamagePercent": 0.75}, 8, "PrimedPointBlank", tags = ["shotgun"], conflicts=["PointBlank"]),
        Mod("PrimedPointBlank5", {"BonusDamagePercent": 0.9}, 9, "PrimedPointBlank", tags = ["shotgun"], conflicts=["PointBlank"]),
        Mod("PrimedPointBlank6", {"BonusDamagePercent": 1.05}, 10, "PrimedPointBlank", tags = ["shotgun"], conflicts=["PointBlank"]),
        Mod("PrimedPointBlank7", {"BonusDamagePercent": 1.2}, 11, "PrimedPointBlank", tags = ["shotgun"], conflicts=["PointBlank"]),
        Mod("PrimedPointBlank8", {"BonusDamagePercent": 1.35}, 12, "PrimedPointBlank", tags = ["shotgun"], conflicts=["PointBlank"]),
        Mod("PrimedPointBlank9", {"BonusDamagePercent": 1.5}, 13, "PrimedPointBlank", tags = ["shotgun"], conflicts=["PointBlank"]),
        Mod("PrimedPointBlank10", {"BonusDamagePercent": 1.65}, 14, "PrimedPointBlank", tags = ["shotgun"], conflicts=["PointBlank"]),

        Mod("ChargedShell", {"BonusElectricity": 0.15}, 6, "ChargedShell", tags = ["shotgun"], conflicts = ["PrimeChargedShell"]),
        Mod("ChargedShell1", {"BonusElectricity": 0.3}, 7, "ChargedShell", tags = ["shotgun"], conflicts = ["PrimeChargedShell"]),
        Mod("ChargedShell2", {"BonusElectricity": 0.45}, 8, "ChargedShell", tags = ["shotgun"], conflicts = ["PrimeChargedShell"]),
        Mod("ChargedShell3", {"BonusElectricity": 0.6}, 9, "ChargedShell", tags = ["shotgun"], conflicts = ["PrimeChargedShell"]),
        Mod("ChargedShell4", {"BonusElectricity": 0.75}, 10, "ChargedShell", tags = ["shotgun"], conflicts = ["PrimeChargedShell"]),
        Mod("ChargedShell5", {"BonusElectricity": 0.9}, 11, "ChargedShell", tags = ["shotgun"], conflicts = ["PrimeChargedShell"]),

        Mod("ChillingGrasp", {"BonusCold": 0.15}, 6, "ChillingGrasp", tags = ["shotgun"]),
        Mod("ChillingGrasp1", {"BonusCold": 0.3}, 7, "ChillingGrasp", tags = ["shotgun"]),
        Mod("ChillingGrasp2", {"BonusCold": 0.45}, 8, "ChillingGrasp", tags = ["shotgun"]),
        Mod("ChillingGrasp3", {"BonusCold": 0.6}, 9, "ChillingGrasp", tags = ["shotgun"]),
        Mod("ChillingGrasp4", {"BonusCold": 0.75}, 10, "ChillingGrasp", tags = ["shotgun"]),
        Mod("ChillingGrasp5", {"BonusCold": 0.9}, 11, "ChillingGrasp", tags = ["shotgun"]),

        Mod("ContagiousSpread", {"BonusToxin": 0.15}, 6, "ContagiousSpread", tags = ["shotgun"]),
        Mod("ContagiousSpread1", {"BonusToxin": 0.3}, 7, "ContagiousSpread", tags = ["shotgun"]),
        Mod("ContagiousSpread2", {"BonusToxin": 0.45}, 8, "ContagiousSpread", tags = ["shotgun"]),
        Mod("ContagiousSpread3", {"BonusToxin": 0.6}, 9, "ContagiousSpread", tags = ["shotgun"]),
        Mod("ContagiousSpread4", {"BonusToxin": 0.75}, 10, "ContagiousSpread", tags = ["shotgun"]),
        Mod("ContagiousSpread5", {"BonusToxin": 0.9}, 11, "ContagiousSpread", tags = ["shotgun"]),

        Mod("IncendiaryCoat", {"BonusHeat": 0.15}, 6, "IncendiaryCoat", tags = ["shotgun"]),
        Mod("IncendiaryCoat1", {"BonusHeat": 0.3}, 7, "IncendiaryCoat", tags = ["shotgun"]),
        Mod("IncendiaryCoat2", {"BonusHeat": 0.45}, 8, "IncendiaryCoat", tags = ["shotgun"]),
        Mod("IncendiaryCoat3", {"BonusHeat": 0.6}, 9, "IncendiaryCoat", tags = ["shotgun"]),
        Mod("IncendiaryCoat4", {"BonusHeat": 0.75}, 10, "IncendiaryCoat", tags = ["shotgun"]),
        Mod("IncendiaryCoat5", {"BonusHeat": 0.9}, 11, "IncendiaryCoat", tags = ["shotgun"]),

        Mod("SeekingFury", {"BonusReload": 0.025}, 6, "SeekingFury", tags = ["shotgun"]),
        Mod("SeekingFury1", {"BonusReload": 0.05}, 7, "SeekingFury", tags = ["shotgun"]),
        Mod("SeekingFury2", {"BonusReload": 0.075}, 8, "SeekingFury", tags = ["shotgun"]),
        Mod("SeekingFury3", {"BonusReload": 0.1}, 9, "SeekingFury", tags = ["shotgun"]),
        Mod("SeekingFury4", {"BonusReload": 0.125}, 10, "SeekingFury", tags = ["shotgun"]),
        Mod("SeekingFury5", {"BonusReload": 0.15}, 11, "SeekingFury", tags = ["shotgun"]),

        Mod("Disruptor", {"BonusImpact": 0.15}, 4, "Disruptor", tags = ["shotgun"]),
        Mod("Disruptor1", {"BonusImpact": 0.3}, 5, "Disruptor", tags = ["shotgun"]),
        Mod("Disruptor2", {"BonusImpact": 0.45}, 6, "Disruptor", tags = ["shotgun"]),
        Mod("Disruptor3", {"BonusImpact": 0.6}, 7, "Disruptor", tags = ["shotgun"]),
        Mod("Disruptor4", {"BonusImpact": 0.75}, 8, "Disruptor", tags = ["shotgun"]),
        Mod("Disruptor5", {"BonusImpact": 0.9}, 9, "Disruptor", tags = ["shotgun"]),

        Mod("Flechette", {"BonusPuncture": 0.15}, 4, "Flechette", tags = ["shotgun"]),
        Mod("Flechette1", {"BonusPuncture": 0.3}, 5, "Flechette", tags = ["shotgun"]),
        Mod("Flechette2", {"BonusPuncture": 0.45}, 6, "Flechette", tags = ["shotgun"]),
        Mod("Flechette3", {"BonusPuncture": 0.6}, 7, "Flechette", tags = ["shotgun"]),
        Mod("Flechette4", {"BonusPuncture": 0.75}, 8, "Flechette", tags = ["shotgun"]),
        Mod("Flechette5", {"BonusPuncture": 0.9}, 9, "Flechette", tags = ["shotgun"]),

        Mod("PointBlank", {"BonusDamagePercent": 0.15}, 4, "PointBlank", tags = ["shotgun"], conflicts=["PrimedPointBlank"]),
        Mod("PointBlank1", {"BonusDamagePercent": 0.3}, 5, "PointBlank", tags = ["shotgun"], conflicts=["PrimedPointBlank"]),
        Mod("PointBlank2", {"BonusDamagePercent": 0.45}, 6, "PointBlank", tags = ["shotgun"], conflicts=["PrimedPointBlank"]),
        Mod("PointBlank3", {"BonusDamagePercent": 0.6}, 7, "PointBlank", tags = ["shotgun"], conflicts=["PrimedPointBlank"]),
        Mod("PointBlank4", {"BonusDamagePercent": 0.75}, 8, "PointBlank", tags = ["shotgun"], conflicts=["PrimedPointBlank"]),
        Mod("PointBlank5", {"BonusDamagePercent": 0.9}, 9, "PointBlank", tags = ["shotgun"], conflicts=["PrimedPointBlank"]),

        Mod("ShotgunBarrage", {"BonusFireRate": 0.15}, 4, "ShotgunBarrage", tags = ["shotgun"]),
        Mod("ShotgunBarrage1", {"BonusFireRate": 0.3}, 5, "ShotgunBarrage", tags = ["shotgun"]),
        Mod("ShotgunBarrage2", {"BonusFireRate": 0.45}, 6, "ShotgunBarrage", tags = ["shotgun"]),
        Mod("ShotgunBarrage3", {"BonusFireRate": 0.6}, 7, "ShotgunBarrage", tags = ["shotgun"]),
        Mod("ShotgunBarrage4", {"BonusFireRate": 0.75}, 8, "ShotgunBarrage", tags = ["shotgun"]),
        Mod("ShotgunBarrage5", {"BonusFireRate": 0.9}, 9, "ShotgunBarrage", tags = ["shotgun"]),

        Mod("Shredder", {"BonusSlash": 0.15}, 4, "Shredder", tags = ["shotgun"]),
        Mod("Shredder1", {"BonusSlash": 0.3}, 5, "Shredder", tags = ["shotgun"]),
        Mod("Shredder2", {"BonusSlash": 0.45}, 6, "Shredder", tags = ["shotgun"]),
        Mod("Shredder3", {"BonusSlash": 0.6}, 7, "Shredder", tags = ["shotgun"]),
        Mod("Shredder4", {"BonusSlash": 0.75}, 8, "Shredder", tags = ["shotgun"]),
        Mod("Shredder5", {"BonusSlash": 0.9}, 9, "Shredder", tags = ["shotgun"]),

        Mod("Blunderbuss", {"BonusCritChance": 0.15}, 4, "Blunderbuss", tags = ["shotgun"]),
        Mod("Blunderbuss1", {"BonusCritChance": 0.3}, 5, "Blunderbuss", tags = ["shotgun"]),
        Mod("Blunderbuss2", {"BonusCritChance": 0.45}, 6, "Blunderbuss", tags = ["shotgun"]),
        Mod("Blunderbuss3", {"BonusCritChance": 0.6}, 7, "Blunderbuss", tags = ["shotgun"]),
        Mod("Blunderbuss4", {"BonusCritChance": 0.75}, 8, "Blunderbuss", tags = ["shotgun"]),
        Mod("Blunderbuss5", {"BonusCritChance": 0.9}, 9, "Blunderbuss", tags = ["shotgun"]),

        Mod("Ravage", {"BonusCritMultiplier": 0.1}, 4, "Ravage", tags = ["shotgun"]),
        Mod("Ravage1", {"BonusCritMultiplier": 0.2}, 5, "Ravage", tags = ["shotgun"]),
        Mod("Ravage2", {"BonusCritMultiplier": 0.3}, 6, "Ravage", tags = ["shotgun"]),
        Mod("Ravage3", {"BonusCritMultiplier": 0.4}, 7, "Ravage", tags = ["shotgun"]),
        Mod("Ravage4", {"BonusCritMultiplier": 0.5}, 8, "Ravage", tags = ["shotgun"]),
        Mod("Ravage5", {"BonusCritMultiplier": 0.6}, 9, "Ravage", tags = ["shotgun"]),

        Mod("TacticalPump", {"BonusReload": 0.1}, 2, "TacticalPump", tags = ["shotgun"]),
        Mod("TacticalPump1", {"BonusReload": 0.2}, 3, "TacticalPump", tags = ["shotgun"]),
        Mod("TacticalPump2", {"BonusReload": 0.3}, 4, "TacticalPump", tags = ["shotgun"]),
        Mod("TacticalPump3", {"BonusReload": 0.4}, 5, "TacticalPump", tags = ["shotgun"]),
        Mod("TacticalPump4", {"BonusReload": 0.5}, 6, "TacticalPump", tags = ["shotgun"]),
        Mod("TacticalPump5", {"BonusReload": 0.6}, 7, "TacticalPump", tags = ["shotgun"]),

        Mod("ToxicBarrage", {"BonusToxin": 0.15, "BonusStatusChance": 0.15}, 4, "ToxicBarrage", tags = ["shotgun"]),
        Mod("ToxicBarrage1", {"BonusToxin": 0.3, "BonusStatusChance": 0.3}, 5, "ToxicBarrage", tags = ["shotgun"]),
        Mod("ToxicBarrage2", {"BonusToxin": 0.45, "BonusStatusChance": 0.45}, 6, "ToxicBarrage", tags = ["shotgun"]),
        Mod("ToxicBarrage3", {"BonusToxin": 0.6, "BonusStatusChance": 0.6}, 7, "ToxicBarrage", tags = ["shotgun"]),

        Mod("BurdenedMagazine", {"BonusMagazine": 0.1, "BonusReload": -0.03}, 4, "BurdenedMagazine", tags = ["shotgun"]),
        Mod("BurdenedMagazine1", {"BonusMagazine": 0.2, "BonusReload": -0.06}, 5, "BurdenedMagazine", tags = ["shotgun"]),
        Mod("BurdenedMagazine2", {"BonusMagazine": 0.3, "BonusReload": -0.09}, 6, "BurdenedMagazine", tags = ["shotgun"]),
        Mod("BurdenedMagazine3", {"BonusMagazine": 0.4, "BonusReload": -0.12}, 7, "BurdenedMagazine", tags = ["shotgun"]),
        Mod("BurdenedMagazine4", {"BonusMagazine": 0.5, "BonusReload": -0.15}, 8, "BurdenedMagazine", tags = ["shotgun"]),
        Mod("BurdenedMagazine5", {"BonusMagazine": 0.6, "BonusReload": -0.18}, 9, "BurdenedMagazine", tags = ["shotgun"]),

        Mod("LingeringTorment", {"BonusStatusDuration": 0.15}, 6, "LingeringTorment", tags = ["shotgun"]),
        Mod("LingeringTorment1", {"BonusStatusDuration": 0.3}, 7, "LingeringTorment", tags = ["shotgun"]),
        Mod("LingeringTorment2", {"BonusStatusDuration": 0.45}, 8, "LingeringTorment", tags = ["shotgun"]),
        Mod("LingeringTorment3", {"BonusStatusDuration": 0.6}, 9, "LingeringTorment", tags = ["shotgun"]),
        Mod("LingeringTorment4", {"BonusStatusDuration": 0.75}, 10, "LingeringTorment", tags = ["shotgun"]),
        Mod("LingeringTorment5", {"BonusStatusDuration": 0.9}, 11, "LingeringTorment", tags = ["shotgun"]),

        Mod("PrimedChargedShell", {"BonusElectricity": 0.15}, 6, "PrimedChargedShell", tags = ["shotgun"], conflicts=["ChargedShell"]),
        Mod("PrimedChargedShell1", {"BonusElectricity": 0.3}, 7, "PrimedChargedShell", tags = ["shotgun"], conflicts=["ChargedShell"]),
        Mod("PrimedChargedShell2", {"BonusElectricity": 0.45}, 8, "PrimedChargedShell", tags = ["shotgun"], conflicts=["ChargedShell"]),
        Mod("PrimedChargedShell3", {"BonusElectricity": 0.6}, 9, "PrimedChargedShell", tags = ["shotgun"], conflicts=["ChargedShell"]),
        Mod("PrimedChargedShell4", {"BonusElectricity": 0.75}, 10, "PrimedChargedShell", tags = ["shotgun"], conflicts=["ChargedShell"]),
        Mod("PrimedChargedShell5", {"BonusElectricity": 0.9}, 11, "PrimedChargedShell", tags = ["shotgun"], conflicts=["ChargedShell"]),
        Mod("PrimedChargedShell6", {"BonusElectricity": 1.05}, 12, "PrimedChargedShell", tags = ["shotgun"], conflicts=["ChargedShell"]),
        Mod("PrimedChargedShell7", {"BonusElectricity": 1.2}, 13, "PrimedChargedShell", tags = ["shotgun"], conflicts=["ChargedShell"]),
        Mod("PrimedChargedShell8", {"BonusElectricity": 1.35}, 14, "PrimedChargedShell", tags = ["shotgun"], conflicts=["ChargedShell"]),
        Mod("PrimedChargedShell9", {"BonusElectricity": 1.5}, 15, "PrimedChargedShell", tags = ["shotgun"], conflicts=["ChargedShell"]),
        Mod("PrimedChargedShell10", {"BonusElectricity": 1.65}, 16, "PrimedChargedShell", tags = ["shotgun"], conflicts=["ChargedShell"]),

        Mod("AmmoStock", {"BonusMagazine": 0.1}, 2, "AmmoStock", tags = ["shotgun"]),
        Mod("AmmoStock1", {"BonusMagazine": 0.2}, 3, "AmmoStock", tags = ["shotgun"]),
        Mod("AmmoStock2", {"BonusMagazine": 0.3}, 4, "AmmoStock", tags = ["shotgun"]),
        Mod("AmmoStock3", {"BonusMagazine": 0.4}, 5, "AmmoStock", tags = ["shotgun"]),
        Mod("AmmoStock4", {"BonusMagazine": 0.5}, 6, "AmmoStock", tags = ["shotgun"]),
        Mod("AmmoStock5", {"BonusMagazine": 0.6}, 7, "AmmoStock", tags = ["shotgun"]),

        Mod("ChillingReload", {"BonusCold": 0.15, "BonusReload": 0.1}, 6, "ChillingReload", tags = ["shotgun"]),
        Mod("ChillingReload1", {"BonusCold": 0.3, "BonusReload": 0.2}, 7, "ChillingReload", tags = ["shotgun"]),
        Mod("ChillingReload2", {"BonusCold": 0.45, "BonusReload": 0.3}, 8, "ChillingReload", tags = ["shotgun"]),
        Mod("ChillingReload3", {"BonusCold": 0.6, "BonusReload": 0.4}, 9, "ChillingReload", tags = ["shotgun"]),
        #-----------------------------#

    ]